# Dockerfile to build based on node24
FROM node:24-alpine

RUN apk add --no-cache git python3 make g++ bash

WORKDIR /build

ARG TAG
RUN git clone https://github.com/mjmeans/KaraokeEternal.git . \
    && git checkout $TAG

RUN npm install --no-audit --no-fund \
    && npm run build \
    && npm install -g . --no-audit --no-fund \
    && rm -rf /build

ENV NODE_ENV=production

VOLUME ["/config","/mnt/karaoke"]
EXPOSE 8080

CMD ["sleep", "999999"]

#CMD ["sh", "-c", "cd / && exec karaoke-eternal-server \
#  -p ${KES_PORT} \
#  --data ${KES_PATH_DATA} \
#  --serverLogLevel ${KES_SERVER_LOG_LEVEL} \
#  --scannerLogLevel ${KES_SCANNER_LOG_LEVEL}"]
